#x=float(input("What is x?"))
#y=float(input("What is Y?"))
#z=int(x) + int(y)
#print(int(x)+int(y))
#z=round(x+y)
#print(f"{z:,}")
x=float(input("What is x?"))
y=float(input("What is y?"))
#z=round(x/y,2)
z=x/y
print(f"{z:.2f}")